### ISSUE TITLE
Imgui wont get setup properly

### ISSUE THREAD

**Issue by hubinger** [GayPig/DirectX11-hook-with-discord#4]
Thanks for your contribution, i debuged everything and tripple checked the patterns. Everything works expect imgui, the hook(s) gets initialized fine, but imgui does not show up. I tried to debug the problem with imgui as well, but couldn’t found an issue. To be sure its not an issue with my processor i removed all xorstr and iat functions. Also i disabled all other overlays on my computer to be sure its not an issue caused by it.

**Comment by GayPig** [comment]
fixed, check last commit
